module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Field', [
      {
        rowId: 1,
        name: 'title',
        type: 'text',
        value: 'Software Quality Assurance',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 1,
        name: 'description',
        type: 'text',
        value: 'An intensive practical course to prepare you for a successful QA career in just 4 weeks',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 1,
        name: 'backgroundImageURL',
        type: 'url',
        value: 'https://uploads-ssl.webflow.com/5c8ff8ef21fa8e172cd8a465/5d2715893854966a256dae76_Group%202.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        rowId: 2,
        name: 'title',
        type: 'text',
        value: 'How it Works',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 2,
        name: 'edge-1',
        type: 'text',
        value: '4-week intensive online training will help you develop technical and communication skills for a successful career in QA.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 2,
        name: 'edge-2',
        type: 'text',
        value: 'Live classes are weekly Sunday to Thursday 9:30–11:30 PM Eastern. After each lesson students get handouts and recording.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 2,
        name: 'edge-3',
        type: 'text',
        value: '1:1 support and mentoring. Students can ask questions during the lessons or after them. Even after the course is over.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 2,
        name: 'edge-4',
        type: 'text',
        value: 'We will make your resume and post it on job sites with proper keywords so you could get tons of calls from recruiters.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 2,
        name: 'edge-5',
        type: 'text',
        value: 'You will learn how to search for a job effectively, answer interview questions and significantly increase chances of getting hired.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 2,
        name: 'edge-6',
        type: 'text',
        value: 'Study first, pay us later. No student loans, no debt, and you won\'t pay a tuition until you land a job making at least $50k a year.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        rowId: 3,
        name: 'title',
        type: 'text',
        value: 'Learn DevOps',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 3,
        name: 'description',
        type: 'text',
        value: 'An intensive practical course to prepare you for a successful DevOps career in just 12 weeks.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 3,
        name: 'backgroundImageURL',
        type: 'url',
        value: 'https://uploads-ssl.webflow.com/5c8ff8ef21fa8e172cd8a465/5e538231eba259546b4261f4_Group%202-p-1600.jpeg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        rowId: 4,
        name: 'title',
        type: 'text',
        value: 'How it Works',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 4,
        name: 'edge-1',
        type: 'text',
        value: '12-week intensive online training after which you can start looking for a mid-level job.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 4,
        name: 'edge-2',
        type: 'text',
        value: 'Live online classes with homework for daily practice. 1:1 support and mentoring, even after the course is over.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 4,
        name: 'edge-3',
        type: 'text',
        value: 'You will learn how to answer interview questions and how to pass job interview coding and other tests.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 4,
        name: 'edge-4',
        type: 'text',
        value: 'We will make your resume of experienced Engineer, so you can aim at $115K+ salary. We provide internships and references.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 4,
        name: 'edge-5',
        type: 'text',
        value: 'The first 2 lessons are FREE. You won`t pay full tuition until you land a job. If you don`t get a job in IT, you won`t owe us anything.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        rowId: 4,
        name: 'edge-6',
        type: 'text',
        value: 'Pay $99 registration fee and 17% of your salary over 24 months (if you don\'t get a job, the course is FREE) OR $999 fee and 10% of the salary over 18 mo.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Field', null, {});
  }
};
