module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Field', [
      {
        sectionId: 1,
        order: 10,
        name: 'title',
        value: 'Software Quality Assurance',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 1,
        order: 20,
        name: 'description',
        value: 'An intensive practical course to prepare you for a successful QA career in just 4 weeks',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 1,
        order: 30,
        name: 'backgroundImage',
        value: 'https://uploads-ssl.webflow.com/5c8ff8ef21fa8e172cd8a465/5d2715893854966a256dae76_Group%202-p-1600.jpeg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 1,
        order: 10,
        name: 'ctaHeader[1].text',
        value: 'Apply Now',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 1,
        order: 10,
        name: 'ctaHeader[1].url',
        value: '#apply-form',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        sectionId: 2,
        order: 10,
        name: 'title',
        value: 'How it Works',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 10,
        name: 'benefits[1].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 20,
        name: 'benefits[1].description',
        value: '4-week intensive online training will help you develop technical and communication skills for a successful career in QA.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 10,
        name: 'benefits[2].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 20,
        name: 'benefits[2].description',
        value: 'Live classes are weekly Sunday to Thursday 7:00–9:00 PM Eastern. After each lesson students get handouts and recording.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 10,
        name: 'benefits[3].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 20,
        name: 'benefits[3].description',
        value: '1:1 support and mentoring. Students can ask questions during the lessons or after them. Even after the course is over.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 10,
        name: 'benefits[4].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 20,
        name: 'benefits[4].description',
        value: 'We will make your resume and post it on job sites with proper keywords so you could get tons of calls from recruiters.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 10,
        name: 'benefits[5].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 20,
        name: 'benefits[5].description',
        value: 'You will learn how to search for a job effectively, answer interview questions and significantly increase chances of getting hired.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 10,
        name: 'benefits[6].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 2,
        order: 20,
        name: 'benefits[6].description',
        value: 'Study first, pay us later. No student loans, no debt, and you won\'t pay a tuition until you land a job making at least $50k a year.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        sectionId: 3,
        order: 10,
        name: 'title',
        value: 'Learn DevOps',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 3,
        order: 20,
        name: 'description',
        value: 'An intensive practical course to prepare you for a successful DevOps career in just 12 weeks.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 3,
        order: 30,
        name: 'backgroundImage',
        value: 'https://uploads-ssl.webflow.com/5c8ff8ef21fa8e172cd8a465/5e538231eba259546b4261f4_Group%202-p-1600.jpeg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 3,
        order: 10,
        name: 'ctaHeader[1].text',
        value: 'Apply Now',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 3,
        order: 10,
        name: 'ctaHeader[1].url',
        value: '#form',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        sectionId: 4,
        order: 10,
        name: 'title',
        value: 'How it Works',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 10,
        name: 'benefits[1].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 20,
        name: 'benefits[1].description',
        value: '12-week intensive online training after which you can start looking for a mid-level job.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 10,
        name: 'benefits[2].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 20,
        name: 'benefits[2].description',
        value: 'Live online classes with homework for daily practice. 1:1 support and mentoring, even after the course is over.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 10,
        name: 'benefits[3].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 20,
        name: 'benefits[3].description',
        value: 'You will learn how to answer interview questions and how to pass job interview coding and other tests.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 10,
        name: 'benefits[4].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 20,
        name: 'benefits[4].description',
        value: 'We will make your resume of experienced Engineer, so you can aim at $115K+ salary. We provide internships and references.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 10,
        name: 'benefits[5].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 20,
        name: 'benefits[5].description',
        value: 'The first 2 lessons are FREE. You won\'t pay full tuition until you land a job. If you don\'t get a job in IT, you won\'t owe us anything.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 10,
        name: 'benefits[6].title',
        value: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 4,
        order: 20,
        name: 'benefits[6].description',
        value: 'Pay $99 registration fee and 17% of your salary over 24 months (if you don\'t get a job, the course is FREE) OR $999 fee and 10% of the salary over 18 mo.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        sectionId: 5,
        order: 10,
        name: 'title',
        value: 'Python intensive course',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 5,
        order: 20,
        name: 'description',
        value: 'An immersive practical course to boost your tech career with the most popular programming language right now.',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 5,
        order: 30,
        name: 'backgroundImage',
        value: 'https://uploads-ssl.webflow.com/5c8ff8ef21fa8e172cd8a465/5e628ca748ce2f379610c987_12312312312.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 5,
        order: 10,
        name: 'ctaHeader[1].text',
        value: 'Apply Now',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 5,
        order: 10,
        name: 'ctaHeader[1].url',
        value: '#form',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        sectionId: 6,
        order: 10,
        name: 'title',
        value: 'Why learn Python now?',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 6,
        order: 10,
        name: 'benefits[1].title',
        value: 'Really easy and fast to learn',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 6,
        order: 20,
        name: 'benefits[1].description',
        value: 'Python is really easy to understand language with friendly syntaxis',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 6,
        order: 10,
        name: 'benefits[2].title',
        value: 'The most popular language',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 6,
        order: 20,
        name: 'benefits[2].description',
        value: 'A lot of employers need Python developers on their projects',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 6,
        order: 10,
        name: 'benefits[3].title',
        value: 'Large community',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 6,
        order: 20,
        name: 'benefits[3].description',
        value: 'There is a large online community of Python users and experts',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 6,
        order: 10,
        name: 'benefits[4].title',
        value: 'Higher Salary',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        sectionId: 6,
        order: 20,
        name: 'benefits[4].description',
        value: 'Python developers earn $116,028 per year on average in the US',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Field', null, {});
  }
};
